project:
  type: website

website:
  title: "Nghia Cao's blogS"
  navbar:
    right:
      - home.qmd
      - about.qmd
      - icon: github
        href: https://github.com/nghiacao2001
format:
  html:
    theme: journal  
    css: styles.css
    background-color: "#f0f0f0"  
    heading-color: "#333333"



